### PR TITLE
RELEASE-3.1.1 - Feature#386

### LINKED ISSUE #386: Capturar solucion de usuario
**Al no estar implementado el endpoint en backend, ponemos console.log con la solución capturada**

TODO: es necesario diseñar una pipe para escapar caracteres clave del standard JSON (otra issue).
**made by Frncesc**
**reviewed by eloi**

### PR DESCRIPTION
**Pull request by fran-cesc**
User solution captured an seen in console.

### CODE REVIEW

**Comment by jonatanvicente** [comment]
This request includes changes at solution.service. However, solution.service.spec.ts (tests) is not implemented. 
Those tests must contains extracts of Challenge Solutions in Java with characters to escape, while the endpoints at backend are implemented.

Please, fix it before requesting a new PR.

**Comment by fran-cesc** [comment]
Test with characters to escape in feature#387 (Pipe to escape java characters)

**Comment by jonatanvicente** [comment]
Please, do not overwrite CodeMirror component with a textarea as it seems at code

**Comment by fran-cesc** [comment]
Textarea overwriting codemirror fixed.
Code written by user appears in different colours (feature#406).

**Pull request merged**
