### PR TITLE
RELEASE-3.1.0 - Feature#271

### LINKED ISSUE #271: Anclado Solutions / Detalles: al enviar un reto, se han de visualizar las soluciones y detalles disponibles
* Es necesario verificar la implementación de que, una vez el usuario envía el reto a la plataforma, se le redirecciona a la pestaña 'Soluciones' y se muestran las soluciones aceptadas.
* Incluye 2 invocaciones a backend: el envío de soluciones y el mostrado de las existentes + testing
* **Es necesario detectar si ya hay solución enviada invocando el endpoint http://{{host}}:{{port}}/solution/user/{idUser}/challenge/{idChallenge}/language/{idLanguage}**
* Véase implementación parcial en **feature#257**

Image

### PR DESCRIPTION
**Pull request by fran-cesc**
- Redireccionado a pestaña soluciones.
- Visualización de soluciones aceptadas.
- Se detecta si el usuario ya ha enviado solución.

Comentarios:

- No en todos los retos se muestra el texto de la solucion, en algunos aparece código java.
- Cuando clicamos en un related, no detecta si el usuario ha enviado solución.
- Peticion de User Solution harcodeada ya que user actual es anonym.

### CODE REVIEW

**Comment by jonatanvicente** [comment]
Ups.... it seems there is a corrupted file in the PR. In addition, all variables included at environment.ts must be in environment.prod.ts

**Comment by jonatanvicente** [comment]
Please, review next details:
* There are some conflicts (see above)
* CHANGELOG must be written only in English
* It seems there is a env var called 'BACKEND_SSO_SOLUTION' at environment.prod with value dummy  :(

**Comment by fran-cesc** [comment]
details fixed.

**Comment by jonatanvicente** [comment]
The request is not redirected appropriately (screenshot attached).
Pasted image

**Comment by jonatanvicente** [comment]
The code sounds good. However there are several conflicts, may be because develop branch have been updated. Please review them and send a new PR. Thks ;)

**Pull request closed without merging**
